### ISSUE TITLE
Agile development sprints for the Voice Assistant application

### ISSUE THREAD

**Issue by M-Usman-Tahir** [M-Usman-Tahir/voice-assistant#2]
## What to do?
- Login Signup pages
- Responsive preview
- Firebase connectivity
- User Authentication
- Documentation

We need to work on the Milestone and must be done at least a day before the deadline.

**Comment by alinaqikhan** [comment]
:zap: On it ...!

**Comment by M-Usman-Tahir** [comment]
Milestone achieved ..! 🎇
